AWSTemplateFormatVersion: "2010-09-09"
Description: HPSkolan Resource Template
Parameters:
  BaseName:
    Description: Base name
    Type: String
    Default: hpskolan-public-prod
  HostedZoneName:
    Description: Hosted zone
    Type: String
    Default: xn--hgskoleprovet-imb.nu.
  DomainName:
    Description: Domain name
    Type: String
    Default: xn--hgskoleprovet-imb.nu
Resources:

  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'www-${BaseName}'
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html

  WebsiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref Bucket
      PolicyDocument:
        Statement:
        - Sid: PublicReadForGetBucketObjects
          Effect: Allow
          Principal: '*'
          Action: s3:GetObject
          Resource: !Join ['', ['arn:aws:s3:::', !Ref 'Bucket', /*]]
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    DependsOn:
    - Bucket
    Properties:
      DistributionConfig:
        Comment: Cloudfront Distribution pointing to S3 bucket
        Origins:
        - DomainName: !Select [2, !Split ["/", !GetAtt Bucket.WebsiteURL]]
          Id: S3Origin
          CustomOriginConfig:
            HTTPPort: '80'
            HTTPSPort: '443'
            OriginProtocolPolicy: http-only
        Enabled: true
        HttpVersion: 'http2'
        DefaultRootObject: index.html
        Aliases:
          - !Sub 'www.${DomainName}'
        DefaultCacheBehavior:
          AllowedMethods:
            - HEAD
            - OPTIONS
            - GET
          Compress: true
          TargetOriginId: S3Origin
          ForwardedValues:
            QueryString: true
            Cookies:
              Forward: none
          ViewerProtocolPolicy: redirect-to-https
        PriceClass: PriceClass_All
        ViewerCertificate:
          SslSupportMethod: sni-only
          AcmCertificateArn: arn:aws:acm:us-east-1:244998676221:certificate/d73f4eeb-ce91-4876-a7f3-694f11805b8e

  NakedBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BaseName
      AccessControl: PublicRead
      WebsiteConfiguration:
        RedirectAllRequestsTo:
          HostName: !Sub 'www.${DomainName}'
          Protocol: https

  NakedCloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    DependsOn:
    - NakedBucket
    - CloudFrontDistribution
    Properties:
      DistributionConfig:
        Comment: Cloudfront Distribution pointing to S3 bucket
        Origins:
        - DomainName: !Select [2, !Split ["/", !GetAtt NakedBucket.WebsiteURL]]
          Id: S3Origin
          CustomOriginConfig:
            HTTPPort: '80'
            HTTPSPort: '443'
            OriginProtocolPolicy: http-only
        Enabled: true
        HttpVersion: 'http2'
        DefaultRootObject: index.html
        Aliases:
          - !Ref DomainName
        DefaultCacheBehavior:
          AllowedMethods:
            - HEAD
            - OPTIONS
            - GET
          Compress: true
          TargetOriginId: S3Origin
          ForwardedValues:
            QueryString: true
            Cookies:
              Forward: none
          ViewerProtocolPolicy: allow-all
        PriceClass: PriceClass_All
        ViewerCertificate:
          SslSupportMethod: sni-only
          AcmCertificateArn: arn:aws:acm:us-east-1:244998676221:certificate/d73f4eeb-ce91-4876-a7f3-694f11805b8e

Outputs:
  WWWWebsiteURL:
    Value: !GetAtt 
      - Bucket
      - WebsiteURL
    Description: URL for website hosted on S3
  WWWBucketSecureURL:
    Value: !Join 
      - ''
      - - 'https://'
        - !GetAtt 
          - Bucket
          - DomainName
    Description: Name of S3 bucket to hold website content
  WWWCloudfrontEndpoint:
    Value: !GetAtt [CloudFrontDistribution, DomainName]
    Description: Endpoint for Cloudfront distribution



  NakedWebsiteURL:
    Value: !GetAtt 
      - NakedBucket
      - WebsiteURL
    Description: URL for naked website hosted on S3
  NakedBucketSecureURL:
    Value: !Join 
      - ''
      - - 'https://'
        - !GetAtt 
          - NakedBucket
          - DomainName
    Description: Name of Naked S3 bucket
  NakedCloudfrontEndpoint:
    Value: !GetAtt [NakedCloudFrontDistribution, DomainName]
    Description: Endpoint for Naked Cloudfront distribution