AWSTemplateFormatVersion: "2010-09-09"
Description: HPSkolan public Resource Template
Parameters:
  BaseName:
    Description: Base name
    Type: String
    Default: hpskolan-public
  DomainName:
    Description: Domain name
    Type: String
    Default: xn--hgskoleprovet-imb.nu
Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: hpskolan-public-prod
  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref Bucket
      PolicyDocument:
        Statement:
          - Action:
              - s3:GetObject
            Effect: Allow
            Resource: !Join ["", ["arn:aws:s3:::", !Ref Bucket, "/*"]]
            Principal:
              CanonicalUser: !GetAtt CloudFrontOriginAccessIdentity.S3CanonicalUserId
  CloudFrontOriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Sub "CloudFront OAI for ${DomainName}"
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    DependsOn:
      - Bucket
    Properties:
      DistributionConfig:
        Comment: HPSkolan
        Aliases:
          - !Ref DomainName
          - !Sub 'www.${DomainName}'
        DefaultCacheBehavior:
          AllowedMethods:
            - HEAD
            - OPTIONS
            - GET
          ForwardedValues:
            QueryString: true
          TargetOriginId:
            Ref: BaseName
          ViewerProtocolPolicy: redirect-to-https
          LambdaFunctionAssociations:
            - EventType: origin-request
              LambdaFunctionARN: arn:aws:lambda:us-east-1:244998676221:function:hpskolan-edge-lambda-OriginRequestLambdaFunction-TTTR4Y8JU9EY:1
            - EventType: viewer-request
              LambdaFunctionARN: arn:aws:lambda:us-east-1:244998676221:function:hpskolan-edge-lambda-ViewerRequestLambdaFunction-1B0A2XK10BMTB:1
          Compress: true
        CustomErrorResponses:
          - ErrorCode: 403
            ResponseCode: 404
            ResponsePagePath: /404.html
          - ErrorCode: 404
            ResponseCode: 404
            ResponsePagePath: /404.html
        DefaultRootObject: index.html
        Enabled: Yes
        HttpVersion: http2
        ViewerCertificate:
          SslSupportMethod: sni-only
          AcmCertificateArn: arn:aws:acm:us-east-1:244998676221:certificate/d73f4eeb-ce91-4876-a7f3-694f11805b8e
        Origins:
          - Id:
              Ref: BaseName
            DomainName: !GetAtt Bucket.DomainName
            S3OriginConfig:
              OriginAccessIdentity: ""
