AWSTemplateFormatVersion: "2010-09-09"
Description: HPSkolan public template
Parameters:
  BaseName:
    Description: Base name
    Type: String
    Default: hpskolan-public
  DomainName:
    Description: Domain name
    Type: String
    Default: www.xn--hgskoleprovet-imb.nu


Resources:
  ViewerRequestLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Description: >
        Lambda function performing redirects
      Code:
        ZipFile: |
          const path = require('path');
          exports.handler = async (event) => {
            const request = event.Records[0].cf.request;
            const domain = 'www.xn--hgskoleprovet-imb.nu';
            // Redirect trailing slashes  
            if (request.uri !== '/' && request.uri.slice(-1) === '/') {
              return {
                status: '301',
                statusDescription: 'Moved permanently',
                headers: {
                    location: [{
                      key: 'Location',
                      value: `https://${domain}${request.uri.slice(0, -1)}`,
                  }]
                }
              }
            }
            return request;
          };
      Handler: index.handler
      MemorySize: 128
      Role: !Sub ${ViewerRequestLambdaFunctionExecutionRole.Arn}
      Runtime: nodejs10.x
      Tags:
        - Key: Domain
          Value: !Ref DomainName

  ViewerRequestLambdaFunctionVersion:
    Type: AWS::Lambda::Version
    Properties:
      FunctionName: !Ref ViewerRequestLambdaFunction
      Description: !Sub "URL rewriting for ${DomainName}"

  ViewerRequestLambdaFunctionExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - edgelambda.amazonaws.com
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
  OriginRequestLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Description: >
        Lambda function performing request URI rewriting.
      Code:
        ZipFile: |
          const path = require('path');
          exports.handler = async (event) => {
            const request = event.Records[0].cf.request;
            const domain = 'www.xn--hgskoleprovet-imb.nu';
            // Redirect trailing slashes  
            if (request.uri !== '/' && request.uri.slice(-1) === '/') {
              return {
                status: '301',
                statusDescription: 'Moved permanently',
                headers: {
                    location: [{
                      key: 'Location',
                      value: `https://${domain}${request.uri.slice(0, -1)}`,
                  }]
                }
              }
            }
            // Rewrite clean URLs (adding index.html)
            if (!path.extname(request.uri)) {
              request.uri = request.uri.replace(/\/?$/, '\/index.html');
            }
            return request;
          };
      Handler: index.handler
      MemorySize: 128
      Role: !Sub ${OriginRequestLambdaFunctionExecutionRole.Arn}
      Runtime: nodejs10.x
      Tags:
        - Key: Domain
          Value: !Ref DomainName

  OriginRequestLambdaFunctionVersion:
    Type: AWS::Lambda::Version
    Properties:
      FunctionName: !Ref OriginRequestLambdaFunction
      Description: !Sub "URL rewriting for ${DomainName}"

  OriginRequestLambdaFunctionExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - edgelambda.amazonaws.com
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole